- .dockerignore
- Dockerfile
- nginx.config
- package-lock.json
- package.json
See task: https://www.pivotaltracker.com/story/show/174105033
- There's no need for a custom Webpack config; CRA already creates an optimized build
- As soon as Azure has been set up, I'll set up Azure infra & update the circleci config to push to an Azure container registry.
For now, I've set up an ACR manually on my private subscription. See here: https://climateminddev.azurewebsites.net/
> Implemented Dockerfile to be able to publish to Azure

- nginx.config
> fix: update typekit domain to any(*).typekit.net

- nginx.config
- Updated style-src with 'unsafe-inline'
`This needs to be reviewed later since 'unsafe-inline' is considered bad practice`
> fix: add unsafe-inline

- src/__tests__/src/PersonalValues.test.tsx
- src/__tests__/src/__components__/CMCard.test.tsx
- src/common/styles/CMTheme.ts
- src/components/CMCard.tsx
- src/components/Router/RouteConfig.ts
- src/components/Router/Router.tsx
- src/contexts/personality.tsx
- src/hooks/useClimatePersonality.tsx
- src/index.tsx
- src/pages/PersonalValues.tsx
- src/types/types.tsx
What type of PR is this? (check all applicable)
☐ ♻️ Refactor
☑ ✨ Feature
☐ 🐛 Bug Fix
☐ 👷 Optimisation
☐ 📝 Documentation Update
☐ 🔖 Release
☐ 🚩 Other
**Description**
- Context Provider and Hook added to bring in api (session-id=1 only for just now)
- New Route Set up for /personal-values
- New CMCard component to pull together some elements of MUI card
- Created Personal Values Component and mounted at /personal-values
**Added tests?**
☑ 👍 yes
☐ 🙅 no, because they aren't needed
☐ 🙋 no, because I need help
**Added to documentation?**
☐ 📜 readme
☑ 🙅 no documentation needed
> 174267357 see climate personality

- cypress/integration/questionnaire.spec.js
Check the button after the questionnaire takes us on to /personal-values
> Check button goes to /personal-values

- src/__tests__/src/__components__/PrevButton.test.tsx
- src/assets/icon-arrow-back.svg
- src/components/PrevButton.tsx
- src/contexts/responses.tsx
- src/pages/Questionnaire.tsx
Implemented a back button in Questionnarie. 
About the logic: the idea is to use the same logic as changing one question forward, but in reverse.
A separate component holds the "view" part which uses props **text**  and **clickPrevHandler**
> 174710980 navigate back on questionnaire

- src/__tests__/src/__components__/PrevButton.test.tsx
- src/pages/Questionnaire.tsx
First question has no back button. Also cleaned up tests.
> No back button present for first question

- src/pages/MeetGuy.tsx
Replaced “personalised solutions to climate change” with “personalized actions to address climate change”.
> incorporate Katharine Hayhoe recommendations

- src/__tests__/src/ClimateFeed.test.tsx
- src/__tests__/src/__components__/CMCard.test.tsx
- src/__tests__/src/__components__/PrevButton.test.tsx
- src/api/getFeed.tsx
- src/api/submitScores.tsx
- src/components/CMCard.tsx
- src/components/Router/RouteConfig.ts
- src/components/Router/Router.tsx
- src/contexts/climateFeed.tsx
- src/contexts/personality.tsx
- src/contexts/questions.tsx
- src/hooks/useClimateFeed.tsx
- src/index.tsx
- src/pages/ClimateFeed.tsx
- src/types/types.tsx
**This PR is to pull the climate feed and display to the user.** 
- Create provider to hold feed data. contexts/climateFeed.tsx
- Create function to pull feed data **getFeed.tsx** 
- Create hook to use feed data **useClimateFeed**
- set up new route /climate-feed
- new page ClimateFeed
- Render basic climate cards to screen with Title and Description
- Activate Link between personality page and feed. 
**Screenshot**
> Cm 7 view climate feed v1

- src/pages/PersonalValues.tsx
Added section with call-to-action as per design for Personal Values page
> Cm 107 climate personality call to actions to match designs

- src/__tests__/src/PersonalValues.test.tsx
- src/__tests__/src/__utilities__/responses.test.tsx
- src/contexts/responses.tsx
- src/hooks/useSession.tsx
- src/pages/PersonalValues.tsx
[https://climatemind.atlassian.net/browse/CM-16](https://climatemind.atlassian.net/browse/CM-16)
- Clicking the retake the quiz button on the personal values page now redirects to the /questionnaire page to allow the user to retake  the quiz: On Click Session id is cleared, Quiz Responses are cleared
- unit tests updated
> Cm 16 ability to retake quiz

- src/api/getPersonalValues.ts
- src/api/getQuestions.ts
- src/contexts/personality.tsx
- src/contexts/questions.tsx
- src/pages/Questionnaire.tsx
Catch block failing to throw error in questions context if the api is offline. Added conditional to check if the data contains questions and answers and throw error if not. 
Have made a same update to personal values context.
> Cm 138 defect question error state

- package-lock.json
- package.json
- src/components/Question.tsx
- src/index.tsx
- Created a Google Tag Manager Account against climatemind.org@gmail.com
- Install react-gtm-module and set up. 
- Set up as per [instructions ](https://www.npmjs.com/package/react-gtm-module)
- Verify tag manager in place using tag assistant chrome extension
> Cm 143 install tag manager

- cypress/fixtures/personal-values.json
- cypress/integration/personalvalues.spec.ts
Cypress test for the personal values page.
> Personal values Cypress test

- public/manifest.json
- src/components/CMCard.tsx
- src/components/PageWrapper.tsx
- src/components/Wrapper.tsx
- src/pages/ClimateFeed.tsx
- src/pages/PersonalValuesFeed.tsx
- src/stories/components/Wrapper.stories.tsx
- src/stories/pages/ClimateFeed.stories.tsx
flexbox layout issues cause in user to appear to navigate to the bottom of the climate feed. 
- Set up **wrapper component** to allow us to wrap pages and sections in a flexbox grid.
-- Wrapper centers the child components in the middle of the page
-- Ability to accept backgroundColor and fullHeight props.
- Wrap Climate feed in wrapper
- Wrap Personal Values Feed (each section) in wrapper
- Add wrapper component to story book
> Cm 128 user not nav to top of clim feed 2

- src/pages/ClimatePersonality.tsx
* Change "Lets find out your climate personality" to read "Let's find out your climate personality"
> Fix typo in intro sentence

- src/components/Router/Router.tsx
> hide app bar on the quiz

- cypress/integration/questionnaire.spec.ts
- cypress/support/commands.ts
- src/common/styles/CMTheme.ts
- src/common/styles/global.scss
- src/components/ExpandableCard.tsx
- src/components/PageWrapper.tsx
- src/components/Question.tsx
- src/pages/ClimatePersonality.tsx
Here are the first changes for the fine-tuning we just talked about. I added more details to the individual commit messages. Let me know if you have questions.
> CM-314 style fine-tuning (part 1)

- src/__tests__/src/PersonalValues.test.tsx
- src/pages/PersonalValuesFeed.tsx
- Updated test to use changed sentence
- Updated page to use changed sentence
> Cm 251 change sentence in personal values

- src/pages/MythFeed.tsx
- change text - change 'fake news' to 'misinformation' in heading
> CM-349 general myths page - change fake news to misinformation in heading

- src/components/CookiesDialog.tsx
This branch updates Line 48 in `CookiesDialog.tsx`
> CM-366 fixed typo in CookiesDialog.tsx

- src/__tests__/src/GetZipCode.test.tsx
- src/pages/GetZipCode.tsx
this branch updates `GetZipCode.tsx` to replace the old sentence with the newly requested sentence.
it also updates `GetZipCode.test.tsx` to make sure the old sentence in the test is replaced with the new one.
> CM-339 modify zipcode sentence

- src/components/MythCard.tsx
- src/components/MythHeader.tsx
- src/helpers/capitalizeFirstLetter.ts
this updates capitalizes the first letter of a sentence in a myth card.
- created capitalizeFirstLetter.ts
- updated MythHeader.tsx
> CM-383 fix text capitalization myths

- src/analytics.ts
- src/components/ActionOverlay.tsx
- src/components/CardOverlay.tsx
- src/components/EffectOverlay.tsx
- src/components/MythOverlay.tsx
- src/components/SolutionOverlay.tsx
- src/stories/components/ActionNodeList.stories.tsx
- src/stories/components/Card.stories.tsx
- src/stories/pages/PageWithBottomMenu.stories.tsx
- src/types/Actions.ts
- src/types/Solutions.ts
- Make sure overlay card always has an iri for effect, solutions, myths
- Add Function to push card click onto datalayer in analytics.ts
- Update More Button on CardOverlay to push iri of card onto the data layer. 
I managed to create  this branch from the wrong base branch so unfortunately a few file changes relate to  *CM-314*
> Cm-325 add card clicks to datalayer

- src/__tests__/src/__components__/BottomMenu.test.tsx
- src/components/ActionNodeList.tsx
- src/components/ActionOverlay.tsx
- src/components/BottomMenu.tsx
- src/components/SolutionOverlay.tsx
- src/pages/SolutionsFeed.tsx
Changed from "Solutions" to "Actions" on climate feed and solution feed. Also on Bottom menu:
> CM-387_Change_the_word_Solution_to_Action

- src/components/AppBar/MenuPaper.tsx
- src/components/AppBar/Socials.tsx
- src/components/Card.tsx
- src/components/CardFoldout.tsx
- src/pages/ClimateFeed.tsx
1. Reduce the space under the header by half.
2. The climate personality long description is aligned
3.  Benevolence card should say "important to you" NOT DONE since it is content /backend issue
4. Twitter link in the hamburger menu added
5. Privacy link in hamburger menu now says Privacy Policy
> Collection of bugs on frontend

- cypress/fixtures/climate-feed.json
- cypress/fixtures/solutions.json
- cypress/integration/climatefeed.spec.ts
- cypress/integration/personalvalues.spec.ts
- cypress/support/commands.ts
- cypress/support/index.d.ts
- src/components/BottomMenu.tsx
- src/components/CardOverlay.tsx
- src/components/SolutionOverlay.tsx
- src/pages/ClimateFeed.tsx
Added cypress test covering climate feed and bottom navigations.
> CM-405 Add cypress test for feed 

- src/pages/Home.tsx
Files updated: `Home.tsx` 
tests pass.
> CM-441 Add beta to intro page.

- src/components/AppBar/AppBar.tsx
- src/components/AppBar/MenuPaper.tsx
- src/components/CardOverlay.tsx
- src/pages/SolutionsFeed.tsx
> Cm 440 fix menu levels

- src/components/ActionOverlay.tsx
- src/stories/components/ActionNodeList.stories.tsx
- src/types/Actions.ts
Added associated myths to ActionOverlay:
> Cm 397 solar wind dont show myths

- package-lock.json
- src/pages/Conversations.tsx
I also modified the package-lock.json file, I'm not sure if these changes are desired but I just added them to my pull request incase they are. Since I just updated some formatting and changed some icons I didn't add any tests.
> CM-430 Fixed formatting in conversations page

- cypress/fixtures/questions.json
- cypress/integration/questionnaire.spec.ts
- cypress/support/commands.ts
- src/components/GreenRadio.tsx
- src/components/Paragraphs.tsx
- src/components/ProgressBar.tsx
- src/components/Question.tsx
- src/pages/Questionnaire.tsx
Update the quiz screen as per new design. Update the tests, although I had to make the quiz test a little worse just now as having issues with the custom commands.
> CM-450_quiz

- src/pages/MythFeed.tsx
I'm really not sure if this was all that was desired from this ticket but I can make more changes if more is needed.
> Just changed h4 to h5

- src/contexts/queryClient.tsx
- src/pages/MythFeed.tsx
- src/pages/SolutionsFeed.tsx
This PR: 
- Sets a default stale time of all react queries to 5 mins to prevent agressive refetching of queries
- prefetches the myths and solutions feed so they load faster
- minor re-factor of the Myths and solutions feed for simplicity.
> CM-509 Set RQuery default stale time and prefetch myths/solutions

- .eslintrc.json
- src/components/MythCard.tsx
- src/components/MythHeader.tsx
Files changed: MythCard.tsx, MythHeader.tsx.
eslintrc commit was just my linter so I unlinted it... 
https://i.imgur.com/GI5HQRD.png
> Cm 423 update myth card to fit new design

- package.json
Updating browser list to show only supported browsers
> Updating browser list

- README.md
- Add section on using npm install / npm i to README. This should now be everything a new person needs to read to run the app.
> CM-583 add instructions on using npm i to README

- src/components/Question.tsx
- src/pages/Questionnaire.tsx
This PR aims to make Questionnarie look good on large screens. Note that apperance for small screens (mobile) have not been changed.
- large screens now look like:
- small screens look like before:
> Cm 517 make quiz responsive

- src/__tests__/src/__components__/AppBar.test.tsx
- src/components/AppBar/MenuPaper.tsx
Remove the whats an ontology option from the top menu
> remove menu option

- cypress/integration/actionsfeed.spec.ts
- cypress/integration/mythsfeed.spec.ts
- src/components/AppBar/MenuDrawer.tsx
- keeps drawer state when navigated to a new tab.
- Added left padding to the drawer item.
@johols
> keeps drawer state when navigated to a new tab and added left padding.

- cypress/integration/invitedUser.spec.ts
- src/components/Router/RouteConfig.ts
- src/components/Router/Router.tsx
- src/pages/Landing.tsx
> added user B landing page

- cypress/integration/personalvalues.spec.ts
- src/analytics.ts
- src/pages/Register.tsx
Ticket: https://climatemind.atlassian.net/browse/CM-748
4th Attempt to submit due to issue with line endings. All initial issues appear to have been resolved now.
Unblocked following discussion with Nick Callaghan  
Currently using UUID to assign signUpId
Created GTM function in analystics.tsx and added function to Register.tsx onEffect.
> CM-748: adds signup page load event to data layer

- env.sh
Removed dependency on .env.development.
When localhosting there will NOT be any REACT_APP_API_URL in the window at all.
> cm-822 docker fix

- cypress/fixtures/register.json
- cypress/integration/register.spec.ts
- src/__tests__/src/__utilities__/password.ts
- src/helpers/validationSchemas.ts
- Update password regex to match new pw requirements
-- 1 number of spacial char
-- between 8-128 chars
- Add unit tests for regex
- Update cypress test
> CM-806_Loosen_PQ_reqs

- src/common/styles/CMTheme.ts
- src/components/AccountIcon.tsx
- src/components/AppBar/AppBar.tsx
- src/components/AppBar/AppBarWithMenu.tsx
- src/components/BottomMenu.tsx
- src/components/ChangePasswordForm.tsx
- src/components/Modal.tsx
- src/components/Router/RouteConfig.ts
- src/components/Router/Router.tsx
- src/components/UpdateEmailForm.tsx
- src/helpers/validationSchemas.ts
- src/pages/ProfileMenu.tsx
- Navigate to the accounts menu page by clicking on the account icon at the top left corner of the navigation bar/menu.
- Click on change password and see the change password modal having change password form.
- Click on update email and see the update email modal having update email form.
https://user-images.githubusercontent.com/22288040/131415063-acbd94b4-a078-41b8-8f75-e2cdef8e0819.mov
> Cm 565 user can view their profile menu

- src/pages/ProfileMenu.tsx
https://user-images.githubusercontent.com/22288040/133922373-f687a080-5000-466f-9de2-b7f2f050e4f1.mov
> added user logout functionality

- src/App.tsx
- src/components/Router/Router.tsx
- src/index.tsx
- src/mocks/browser.js
- src/mocks/handlers.js
- src/mocks/responseBodies/getAlignment.js
- src/mocks/responseBodies/getSingleConversationResponse.js
- src/mocks/responseBodies/personalValuesResopnse.js
- src/mocks/responseBodies/postAlignment.js
- src/mocks/useMSW.tsx
- src/pages/dev/DevMenu.tsx
Add Mock Service Worker to the app and /dev menu to allow chnaging of MSW settings. 
1. Start the app in the usual way with npm start.
2. Visit /dev to toggle MSW settings
3. See mocked Questions response
I've written some docs [here](https://climatemind.atlassian.net/wiki/spaces/CLIM/pages/433848321/Mock+Service+Worker)
There is also a [demo video](https://www.loom.com/share/263e42a064f043d49d088539fc00783c).
> CM-974_set_up_msw_for_browser

- src/api/postSharedImpacts.ts
- src/common/styles/CMTheme.ts
- src/components/Card/Card.tsx
- src/mocks/handlers.js
- src/mocks/responseBodies/postSharedImpactsResponse.js
- src/mocks/useMSW.tsx
- src/pages/userB/SharedImpacts/SharedImpacts.stories.tsx
- src/pages/userB/SharedImpacts/SharedImpacts.test.tsx
- src/pages/userB/SharedImpacts/SharedImpacts.tsx
- src/pages/userB/SharedSolutions/SharedSolutions.stories.tsx
Based on develop branch, so all the latest changes included.
> CM-957 User B selects impacts

- src/pages/userB/ShareSummary/ShareSummary.tsx
Bugfix: instead of hardcoded values, we now use data from backend
> Cm share summary bugfix

- cypress/integration/landingUserB.spec.ts
- cypress/integration/sharedImpacts.spec.ts
- src/components/MythHeader.tsx
- src/components/ValueCard/ValueCard.tsx
- src/helpers/capitalize.spec.ts
- src/helpers/capitalize.ts
- src/helpers/capitalizeFirstLetter.ts
- src/hooks/useGetOneConversation.ts
- src/hooks/useLocalStorage.tsx
- src/pages/userB/CoreValues.tsx
- src/pages/userB/ShareSummary/ShareSummary.tsx
- src/pages/userB/Shared/Shared.tsx
objective:
- store userA name property in local-storage
- show userA name in coreValues userB page
JIRA: https://climatemind.atlassian.net/browse/CM-1039
> [CM-1039] - user A name should appear in User B summary page instead of "your friend"

- cypress/integration/landingUserB.spec.ts
- cypress/integration/sharedImpacts.spec.ts
- src/components/MythHeader.tsx
- src/components/ValueCard/ValueCard.tsx
- src/helpers/capitalize.spec.ts
- src/helpers/capitalize.ts
- src/helpers/capitalizeFirstLetter.ts
- src/pages/userB/ShareSummary/ShareSummary.tsx
- src/pages/userB/Shared/Shared.tsx
**Objective:**
Create a function to format every work in a phrase and return it capitalized. With this additional function, every word that uses it in the code will have a formatted and expected result.
Also right now this function will be the standard function in the app to do it.
JIRA: https://climatemind.atlassian.net/browse/CM-1044
> [CM-1044] feature: create a function to make every word in a phrase capitalized

- src/pages/SharedValues/SharedValues.tsx
objective:
- show all the content on the screen correctly for the mobile screen
JIRA: https://climatemind.atlassian.net/browse/CM-1040
> [CM-1040] - Overall similarity percentage value hidden under shared impacts button when viewed on mobile for User B

- .gitignore
- Dockerfile.dev
- Dockerfile.m1
- package.json
objective:
in mac m1 we're getting an error related to **puppeteer**. To solve it I added a code in the **Dockerfile.dev** to uncomment under this situation.
> fix: add code to make able to run the frontend docker

- README.md
to match Developer Quick Start Page on confluence.
> readme updates to match Developer Quick Start

- cypress/integration/conversations.spec.ts
- cypress/integration/invitedUser.spec.ts
- src/__tests__/src/ConversationsDashboard.test.tsx
- src/__tests__/src/__components__/DrawerDashboard.test.tsx
- src/components/ConversationIntroCard.tsx
- src/components/ConversationsList.tsx
- src/components/DrawerDashboard.tsx
- src/pages/ConversationsDashboard.tsx
The design teams made a request to change the styling for the 'Talk' page. More information about that can be found in the Jira ticket: [https://climatemind.atlassian.net/browse/CM-1093](https://climatemind.atlassian.net/browse/CM-1093)
I also added an information card at the top of the conversations list, like it can be seen here:
[https://www.figma.com/file/ICtHOAJzuFnEG8ANfXeWix/cm_pwa_design?node-id=1972%3A9279](https://www.figma.com/file/ICtHOAJzuFnEG8ANfXeWix/cm_pwa_design?node-id=1972%3A9279)
> CM-1093: Design updates for Talk page to create link

- cypress/integration/conversations.spec.ts
- src/components/AccountIcon/AccountIcon.stories.tsx
- src/components/Router/PrivateRoute.tsx
- src/contexts/auth.tsx
- src/hooks/auth/useAuth.tsx
- src/hooks/auth/useRefresh.tsx
- src/hooks/auth/useRegister.ts
- src/types/Auth.ts
** added an isLoggedIn state to the auth context
> Cm 1113 access specific conversation from link user a

- src/pages/userB/Landing.tsx
Kameron mentioned in the meeting, that there's a missing space on the landing page for userB.
**Before**
**After**
**Also no problem with different screen sizes**
> Add a missing space in userB's landing page

- src/pages/ConversationsDashboard.tsx
In Desktop mode:
In Mobile mode:
> CM-1114: Better create link instructions

- src/pages/ConversationsDashboard.tsx
On my phone everything looked properly, but on Kamerons phone, the page wasn't scrolled to the top, so I try to enforce that it is scrolled to the top of the page.
> CM-1114: Better create link instructions (Bugfix)

- cypress/integration/conversations.spec.ts
- src/components/ConversationCard/ConversationCard.test.tsx
- src/components/ConversationCard/ConversationCard.tsx
As long as the userB hasn't completed the quiz, userA gets the notification on that card to wait for an email.
> CM-1115: Better convo card initial state screen

- src/pages/userB/HowCMWorks.tsx
- src/pages/userB/Shared/Shared.tsx
* removed all mentions of rewards from user B journey
> remove rewards text

- cypress/integration/alignment.spec.ts
- cypress/integration/userBOnboarding/consent.spec.ts
- cypress/integration/userBOnboarding/landingUserB.spec.ts
- src/api/apiHelper.ts
- src/api/getAlignment.ts
- src/api/postSession.ts
- src/components/ConversationRatingButton/ConversationRatingButton.tsx
- src/components/CookiesDialog.tsx
- src/contexts/session.tsx
- src/hooks/useUserB.ts
- src/pages/userB/Landing.tsx
- src/pages/userB/ShareSummary/ShareSummary.tsx
- src/pages/userB/Shared/Shared.tsx
The userB journey worked completely so that he can share his results with userA. However, when afterwards entering the link again into the browser, the 'shared' and especially the 'shared-summary' page had issues of continuously loading or showing no values. This should now be fixed.
> Bug for pages 'shared' and 'shared-summary'

- src/components/CookiesDialog.tsx
https://user-images.githubusercontent.com/78958483/198602212-94a4b3ee-dd37-4075-939d-22c5ef9c5efd.mp4
> CM-1126: Add 'Reject All' button to cookies dialog

- cypress/integration/accountMenu.ts
- cypress/integration/login.spec.ts
- cypress/integration/onboarding.spec.ts
- src/__tests__/src/Home.test.tsx
- src/pages/Home.tsx
> CM-1127: Update onboarding screen text

- src/analytics.ts
- src/components/AppBar/AppBarWithMenu.tsx
- src/components/BottomMenu/BottomMenu.tsx
Added tracking to conversations button on app bar.
- *#398*
- [X ] The PR contains new PyTest unit/integration tests for any function or functional added. 
- [ X] The PR changes existing PyTest unit/integration tests to keep all tests up to date.
- [ X] The PR does not lead to degradation in unit test coverage.
- [ X] Project parts affected by changes in this PR was tested manually on your local (using Postman or in any other way).
> add tracking to conversations button

- package-lock.json
- package.json
- src/services/analytics-service/AnalyticsService.ts
- src/services/analytics-service/IAnalyticsEvent.ts
- src/services/analytics-service/events.ts
- src/services/analytics-service/index.ts
Copied form native app:
- IAnalyticsEvent
- AnalyticsService
- events
Some changes have already been merged into develop.
Should be fine to just approve it.
> Create analytics service

- .prettierrc
- src/pages/UserBPages/QuizPageUserB.tsx
The issue is that when a user does the questions, on the final question it's supposed to then do a post request. It does this but there is an error that there aren't enough answers and when I place some carefully considered consoles I can see there are only 9 being submitted and there should be 10.
Fix was to put the SubmitAnswers logic into a Useeffect  as below:
```
useEffect(() => {
if (currentQuestionNumber === 11) {
submitAnswers(1, true);
navigate(ROUTES.USERB_CORE_VALUES_PAGE + '/' + conversationId);
}
}, [currentQuestionNumber]);
```
#468 
closes #468 
- *Part 1*
- *Part 2*
> [CLOSES #468] Fix Answer Submission Error When Doing the Quiz from the Conversations modal link

- .prettierrc
- src/pages/UserBPages/UserBLandingPage.tsx
- src/router/Router.tsx
When pasting in the link from the conversation modal The page loaded but the UserNameA was missing. 
The issue was that the useEffect in the UserBLandingScreen component was missing 'conversation' from the dependency array. This has now been added. See below. 
useEffect(() => {
if (sessionId && conversation && conversationId) {
dispatch(setUserAName(conversation.userA.name));
recordUserBVisit(conversationId);
if (conversation.consent) {
navigate(`${ROUTES.USERB_SHARED_SUCCESS_PAGE}/${conversationId}`);
}
}
}, [sessionId, conversation, conversationId]);
closes [466](https://github.com/ClimateMind/climatemind-frontend/issues/466)
- *Part 1*
- *Part 2*
> [CLOSES #466] Fix Missing UserAName on UserBLandingPage 

- package-lock.json
Explain the **details** of making this change. 
Please provide enough information so that others can review your pull request
- *#XX1*
- *#XX2*
- *Part 1*
- *Part 2*
> Minor Change - Updating package.lock. Needs approval

- public/index.html
- src/shared/components/CmTypography.tsx
Explain the **details** of making this change. 
Please provide enough information so that others can review your pull request
- *#XX1*
- *#XX2*
- *Part 1*
- *Part 2*
> fix broken nunito font

- nginx.config
updating nginx to try and fix google auth errors.
> chore: Clean up nginx.config file

- src/features/auth/components/GoogleLogin.tsx
- src/features/auth/hooks/useLogin.tsx
- src/pages/UserBPages/UserBLoginPage.tsx
- src/pages/UserBPages/UserBSharedSuccessPage.tsx
- src/pages/UserBPages/UserBSharedSummaryPage.tsx
- src/pages/UserBPages/UserBSignUpPage.tsx
- src/shared/hooks/useApiClient.tsx
Extended the code logic for the GoogleLogin component to include userb journey. I still need to refactor for typescript and clean up duplicate code, possibly refine into hooks or helper functions.  I will do the refactoring in a new PR but want to get this onto the test env ready to demo at the meeting.
Closes #665
> Closes [665] - Create userb google login and sign in
