.circleci/config.yml, .gitignore, README.md, cypress.json
Updates CI config so videos of the Cypress' tests (if a test fails, using the video is often the easiest way to see exactly why) and any screenshots that are captured (Cypress automatically captures a screenshot on a failure) are stored in Circle CI.
Also updates Cypress reporting so it outputs to an xml file, which CircleCI can then use.
See the artifacts tab for videos/screenshots, and the tests tab the nicely formatted xml - https://app.circleci.com/pipelines/github/ClimateMind/climatemind-frontend/20/workflows/9920f6a7-2766-4cf3-9ce5-8937454c5b84/jobs/44
=> Update Cypress ci config

cypress.json, package-lock.json, package.json
Upgrades Cypress to v5, changelog is here - https://docs.cypress.io/guides/references/changelog.html#5-0-0
Major new feature is test retries, which I've enabled. There's an argument that retries should be needed as tests/applications shouldn't be flakey. In my opinion though, they realistically can be and if a test fails due to flake in CI, I'd rather it then passes on a 2nd attempt and doesn't hold up our development process. We can then look into the reason it needed to retry without blocking any other work (with the scale of the app, I'm not expecting this to happen very often, if at all).
=> upgrade to cypress 5

cypress/integration/homepage.spec.ts, cypress/plugins/index.js, cypress/support/commands.ts, cypress/support/helpers.ts, cypress/support/index.d.ts, cypress/support/index.ts, package-lock.json, package.json
Introduces cypress-axe to our test suite to allow simple accessibility testing (https://github.com/avanslaars/cypress-axe).  My aim is just that we'll run the custom command on each page as we test them.
Automated accessibility testing is never perfect, but it's a starting point and will catch some violations.
I've set it up to only fail on serious and critical failures, there are currently three moderate failures on the homepage, see https://dequeuniversity.com/rules/axe/3.5 for fuller descriptions of them:
| id | impact | description |
| --- | --- | --- |
| landmark-one-main | moderate | Ensures the document has only one main landmark and each iframe in the page has at most one main landmark |
| page-has-heading-one | moderate | Ensure that the page, or at least one of its frames …
=> test accessibility with cypress-axe

cypress.json, cypress/integration/homepage.spec.ts
Changes the viewport size that all the Cypress tests will use to be that of an iphone-x (sizes taken from https://docs.cypress.io/api/commands/viewport.html#Arguments).
Note that Percy will still be capturing at 3 different sizes so any visual anomalies at different sizes should be caught there.
=> Cypress viewport size

.env.production
We have an environment variable REACT_APP_API_URL configured with the backend API url in Azure but application doesn't seem to be aware of it. Hence we are facing an `undefined` value in the react application
- `.env.production` file is added to hold the prod backend url
- This will be picked up by the build scripts and made available for the application
---
Environment variables are setup during the build process of react scripts
- [CRA build script](https://github.com/facebook/create-react-app/blob/025f2739ceb459c79a281ddc6e60d7fd7322ca24/packages/react-scripts/scripts/build.js#L23
)
- [CRA environment variable setup during build process](https://github.com/facebook/create-react-app/blob/025f2739ceb459c79a281ddc6e60d7fd7322ca24/packages/react-scripts/config/env.js#L104) …
=> fix: env file for api url

cypress/integration/questionnaire.spec.ts, cypress/support/commands.ts, cypress/support/index.d.ts
This tests navigating forward and back using the new back button introduced [here](https://github.com/ClimateMind/climatemind-frontend/pull/44)
Added commands for the back and forward navigation functionality to improve readability as this seems like something we might need to do a lot in these tests.
=> [CM-108] add test for back button navigation

src/components/Question.tsx, src/pages/Questionnaire.tsx
The content on the questions page moved around when a user changed questions. This pull request fixes that by:
- useMediaQuery hook from Material UI to add different styling for different screen sizes
=> CM-142 question styling

src/__tests__/src/PersonalValues.test.tsx, src/contexts/personality.tsx, src/contexts/questions.tsx, src/hooks/useClimatePersonality.tsx, src/hooks/useQuestions.tsx, src/pages/PersonalValues.tsx
[Cm 139 handle error personal values fail to load](https://climatemind.atlassian.net/browse/CM-139)
As per CM-138 but for personal values
- update personality context to have isError and isLoading
- update usePersonality hook
- update Personal Values page to show error  and loading based on hook states.
=> Cm 139 handle error personal values fail to load

src/api/getPersonalValues.ts, src/pages/ClimateFeed.tsx, src/types/types.tsx
- Add imageUrl to climate effect type and image card
- The back returns a default imageurl when the is no image available. In practice just now it means the api always returns the same image url
Testing - In order to test this branch please use the following backend branch [https://github.com/ClimateMind/climatemind-backend/tree/local_db_solution](https://github.com/ClimateMind/climatemind-backend/tree/local_db_solution)
=> Cm 80 show images for efects fe

nginx.config
Update the CSP to allow access to google tag manager and images from any src. We may need to go back and be more restrictive in the future. 
Tested agains docker build to replicate production and seems to be working although as the Tag Manager Container has [not been published yet getting a 404 back form google. ](https://support.google.com/tagmanager/thread/10386291?hl=en)
=> CM-143 Update CSP - Defect Google Tag Manager

cypress/integration/errorpages.spec.ts, src/pages/Error404.tsx
Adds Percy snapshots of the error pages, so they can't be accidentally broken by a css change somewhere else.
=> CM-187 Percy snapshots of error pages

src/__tests__/src/__components__/CMCard.test.tsx, src/common/styles/CMTheme.ts, src/components/ActionHeadline.tsx, src/components/CMCard.tsx, src/components/CMCardOverlay.tsx, src/pages/ClimateFeed.tsx, src/stories/components/ActionHeadline.stories.tsx, src/stories/components/CMCard.stories.tsx, src/stories/pages/ClimateFeed.stories.tsx, src/types/types.tsx
Added component ActionHeadline with corresponding stories and tests. The yellow element doesn't show up 
yet since there is no data to show from backend. With mocked data in Storybook we have this look:
=> added ActionHeadline w corresponding stories and tests

src/components/CMCard.tsx, src/components/CMCardFoldout.tsx, src/components/CMCardOverlay.tsx, src/pages/ClimateFeed.tsx, src/types/types.tsx
- Update the climate feed card to show the short desc
- Update the foldout to show short + long desc
=> Cm 220 effect cards show correct descriptions

src/components/CMCard.tsx, src/components/CMCardOverlay.tsx, src/pages/ClimateFeed.tsx, src/stories/components/CMCard.stories.tsx
- Overlay component need a bit of re-arranging so as to use <DialogContent> instead of <CMCard>
- Set Dialog scroll prop to "paper" this makes the card scroll rather than the whole screen
- Use position sticky on Close Area so that is fixed on screen (ordinarily this is not needed but was required in this case to make the transition work) 
- made updated the data going into the storybook for the overlay to simulate some long content
The card can now scroll but the close controls stay on the screen
=> CM-226 Overlay card can scroll with long content

src/components/AppBar/AppBar.tsx
Small pull request to hide the app bar when scrolling to allow then user more space for content. 
We might want to later look to only scrolling on certain screen sizes but for just now scrolls away on all screens.
=> Cm 314 hide app bar on scroll

src/components/ScrollToTopOnMount.tsx, src/pages/ClimateFeed.tsx, src/pages/GetZipCode.tsx, src/pages/Home.tsx, src/pages/MythFeed.tsx, src/pages/PrivacyPolicy.tsx, src/pages/SolutionsFeed.tsx, src/pages/SubmitQuestionnaire.tsx
This feature creates the `ScrollToTopOnMount.tsx` component and imports it into several page components.
There is a more elegant way to do this:
In Router/BrowserRouter: you can do this:
```
<Router onUpdate={() => window.scrollTo(0, 0)}}>
```
But due to me being new to typescript, I'm not sure how to solve TS yelling at me for this more elegant approach: 
however the pushed approach has its pros, what if you don't want to scroll to top on mount for every component? that way you can just import  `ScrollToTopOnMount.tsx` to any page that needs it, additionally, I'm not sure how the sticky navbar would react to the other approach that I tried.
=> CM-343 scroll to top on mount

src/__tests__/src/Home.test.tsx, src/components/AppBar/AppBar.tsx, src/components/BottomMenu.tsx, src/components/PageWrapper.tsx, src/components/PrevButton.tsx, src/pages/ClimateFeed.tsx, src/pages/ClimatePersonality.tsx, src/pages/Home.tsx, src/pages/MeetGuy.tsx, src/pages/MythFeed.tsx, src/pages/PersonalValuesFeed.tsx, src/pages/Questionnaire.tsx, src/pages/SolutionsFeed.tsx, src/pages/SubmitQuestionnaire.tsx
- Adjusted the meetguy page so that top element didn't take up 3/4 of the screen on larger devies.
- Tweaked all the feed pages to make sure the card sizes are responsive and consistent accross, Personal Values, Climate feed, Myth Feed, Solutions Feed.
=> CM-314 Layout tweaks - Make sure card sizes responsive and consistent

src/__tests__/src/PersonalValues.test.tsx, src/pages/PersonalValuesFeed.tsx
This feature updates `PersonalValuesFeed.tsx` to match the design provided at: https://xd.adobe.com/view/c23372e2-dc1f-4bfb-806d-a0220509874f-9760/screen/4e0b28b1-9fb2-4815-abf7-bcbf6c71954c/
it doesn't change the text. as requested.
=> CM-365 change in design of pv page

src/__tests__/src/__components__/CardHeader.test.tsx, src/components/CardHeader.tsx, src/pages/ClimateFeed.tsx, src/stories/components/CardHeadline.stories.tsx, src/types/types.tsx
Backend changed `isPossiblyLocal` from being a boolean to either 0 or 1.
- Updated types and conditional check to display the icon. 
- Added a conditional to make sure "Local Effect" pretitle is only show when there `isLocal === 1`
=> CM-362 local impacts display incorrectly

src/components/ActionOverlay.tsx, src/components/EffectOverlay.tsx, src/components/SolutionOverlay.tsx, src/pages/Conversations.tsx
This card resolves [CM-382 Remove short description from all overlays](https://climatemind.atlassian.net/browse/CM-382) and [CM-395 - Add hyperlink to text in Conversations](https://climatemind.atlassian.net/browse/CM-395)
=> CM-382 remove short desc from overlays & add link to conversations

src/components/MythHeader.tsx
This feature updates `MythHeader.tsx` and removes the quotation marks from myths and truths, and indents the text instead.
=> CM-425 remove quatation marks from myths

cypress/integration/climatefeed.spec.ts, src/components/AppBar/MenuPaper.tsx, src/components/AppBar/Socials.tsx, src/components/CardHeader.tsx, src/components/CardOverlay.tsx, src/pages/ClimateFeed.tsx, src/pages/Home.tsx, src/pages/MeetGuy.tsx, src/pages/PrivacyPolicy.tsx, src/pages/Questionnaire.tsx
Went through Kay's bug list and tried to squash as many simple ones as possible. 
**Titles for feed and solutions being title-case CM-413**
**Close button is too big and too spaced apart on Overlay CM-420**
**hamburger menu - link list should be reordered. CM-434 and CM-433** 
Also fixed padding
**Americanise “...personalized solutions... “ on 1st orange screen CM-408**
**Catalyzing Climate Action shouldn't be capitalised. CM-406**
**Privacy Policy should have a white background colour CM-437**
=> Mon various visual tweaks

src/components/CardOverlay.tsx
It's only a one line change removing a padding: 0 for the button.
=> One line change in card overlay to fix misaligned button

cypress/integration/personalvalues.spec.ts, cypress/integration/questionnaire.spec.ts, src/__tests__/src/GetZipCode.test.tsx, src/api/postZipcode.ts, src/hooks/useQuiz.tsx, src/pages/GetZipCode.tsx, src/pages/PersonalValuesFeed.tsx
- the user can now submit the zip cod after reading Personal values
- the zip submit page has moved. The page flow is now:
to:
to:
to:
to:
=> Cm 466 zip code after personal values results

cypress/integration/actionsfeed.spec.ts, cypress/integration/climatefeed.spec.ts, cypress/integration/menubar.spec.ts, cypress/integration/mythsfeed.spec.ts, cypress/integration/personalvalues.spec.ts, src/__tests__/src/ClimateFeed.test.tsx, src/components/AppBar/AppBar.tsx, src/components/AppBar/MenuPaper.tsx, src/components/AppBar/Socials.tsx
The ticket here was to fix a text contrast issue which mean a11y checks had been disables in the quiz (i think). This had alreay been fix but in the course of investigating I noticed that check were missing on some pages. 
- Added a11y check to any pages where this was not being checked
- Had to make some changes to the top menu to pass accesability. 
Note:  [I encountered this issue with mui](https://github.com/mui-org/material-ui/issues/18935) which i had to resolve by passing TransitionProps.
=> CM-11_fix_a11y_issues

package-lock.json, package.json, src/analytics.ts, src/api/postScores.ts, src/contexts/session.tsx, src/hooks/useQuiz.tsx, src/hooks/useSession.tsx, src/pages/SubmitQuestionnaire.tsx, src/types/Session.ts
This PR is to allow analysts to track the number of users not completing the quiz. 
- Add a quizSessionId (uuid) to the session provider which is generated every time the quiz is started. 
- push this  quiz session id to the Data layer when the quiz is started
- push the quizSession Id along with the question when each question is answered
=> CM-323 add quiz completion to data layer

src/components/AppBar/Socials.tsx, src/components/BottomMenu.tsx, src/components/CardOverlay.tsx, src/components/Wrapper.tsx, src/pages/ClimateFeed.tsx, src/pages/MythFeed.tsx, src/pages/SolutionsFeed.tsx
This PR addresses the following 3 issues: 
CM-422 - Scale/position of bottom-menu changes between pages (iphone 5s)
CM-424 - Remove Logo icon from page headers
CM-421 - Action icon in bottom-menu aren’t the right size - path should be 20px high
Screenshots attached from an iphone 5s. Initially picked up cm-422, issue was a min width was set which was greater than the 5s screen width. Reduced with to allow screens down to 320px and tested through the app. This fixed a number of other issues in the smaller screen size so resolved them too. 
**Out of scope**
The bottom menu still creeps over the allowed space by a couple of px. Unless we change conversations on the menu to something shorter there is no way round that for now.
=> CM-422_width_fix_bottom_menu

src/components/CardHeader.tsx, src/stories/components/CardHeadline.stories.tsx
Fixed the alignment of card header content, see image:
=> Cm 363 card header in climate personality displays incorrectly on widescreen

src/components/CardHeader.tsx, src/components/TabbedContent.tsx
This PR contains 2 bug fixes: CM-426 and CM-531
- CM-426 correct color on inactive Source and details, header displays correctly
before:
after:
- CM-531 Myth header displays wrongly
after:
and:
=> CM-426_Sources/Details tab unselected correct color

src/components/AppBar/PageWithAppBottomBar.tsx
=> Fixed: Responsive menu gets wrong icon position for some screen sizes

src/components/AppBar/MenuPaper.tsx
Bugfix: this issue appears because the set of questions was not reset when retaking quiz. Triggered in the MenuPaper component, the link to retake quiz:
Also fixes ticket CM-643 Trying to get personal values after retaking the quiz redirects to the front page
=> Retaking the PVQ after completing 20 questions restarts the quiz at question 11

.circleci/config.yml, cypress/integration/personalvalues.spec.ts, nginx.config, package.json, src/__tests__/src/SubmitSetOne.test.tsx, src/__tests__/src/SubmitSetTwo.test.tsx, src/api/postScores.ts, src/components/BottomMenu.tsx, src/hooks/useAuth.tsx, src/hooks/usePostScores.tsx, src/pages/Login.tsx, src/pages/Register.tsx, src/pages/SubmitSetOne.tsx, src/pages/SubmitSetTwo.tsx
To allow the user to retake the quiz and get the correct feed back the we need to update the users session id. In order to do this the backend have updated the scores endpoint. When a user is authenticated the JWT should be passed with the call to `/scores`. The backend will then assign the user id in the token to the sessionId. 
To do this the following was done. 
- Updated the post scores function to allow the token to be optionally passed
- Refactored the posting scores logic into a hook `usePostScores` so that it user react-query and is just a bit neater in generel.
- When a the user is logged in the header is now passed with the api call:
`Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeK …
=> CM-700_FE__User_can_retake_quiz

src/__tests__/src/__components__/AppBar.test.tsx, src/__tests__/src/__components__/AppBarWithMenu.test.tsx, src/components/AppBar/AppBar.tsx, src/components/AppBar/AppBarWithMenu.tsx, src/components/AppBar/MenuDrawer.tsx
- The menu for desktops is now a drawer:
Loggged in and with AppBarMenu:
- The menu items can be hovered with a poiner cursor and highlighted
- For desktops, the menu does not disappear when scrolling
=> Cm 629 update top menu drawer for desktop design

src/components/AppBar/AppBarWithMenu.tsx
Here is the change I added.
Pushes the hamburger menu icon to the far right of the navigation bar.
https://user-images.githubusercontent.com/22288040/122650201-3e644880-d13a-11eb-80a1-61f62e6e915b.mov
@johols
=> pushed the hamburger menu to the far right of the navigation bar

cypress/integration/climatefeed.spec.ts, src/__tests__/src/Conversations.test.tsx, src/__tests__/src/__components__/BottomMenu.test.tsx, src/components/AppBar/PageWithAppBottomBar.tsx, src/components/BottomMenu.tsx, src/components/PageTitle.tsx, src/pages/Conversations.tsx
Conversations page matches design. Note that the route is still /conversations. In future we might consider changing it to /talk
and:
=> CM-693: Prepare dummy intro page with button

src/pages/Home.tsx, src/pages/StartQuiz.tsx
Ticket: https://climatemind.atlassian.net/jira/software/projects/CM/boards/1?selectedIssue=CM-800
Added height of 50vh and swapped min-height to absolute units to prevent component ever getting too small to hold content. 
Found bug in Home.tsx and StartQuiz.tsx so edited both files.
=> CM-800: White text and image overlaps above elements on home page

src/api/getFeed.ts, src/api/getMyths.ts, src/api/getOneMyth.ts, src/api/getPersonalValues.ts, src/api/getSolutions.ts, src/api/postLogin.ts, src/api/postLogout.ts, src/api/postRefresh.ts, src/api/postRegister.ts, src/api/postScores.ts, src/api/postSubscriber.ts, src/api/postZipcode.ts, src/hooks/useClimateApi.ts, src/hooks/useSession.tsx
Add X-Session-Id header containing the session ID to all requests after a session id is obtained.
- Set up an axios instance called climate api
- Change all api call to use new instance
- Used interceptor to add X-Session-Id custom header to all api calls once a sesion id is obtained. 
There is a demo [here](https://www.loom.com/share/7f5032d1c6c6490793b244bc3133fbd0)
=> CM-771_session_id_with_req_headers

cypress/integration/invitedUser.spec.ts, cypress/integration/personalvalues.spec.ts, cypress/support/commands.ts, src/contexts/queryClient.tsx, src/contexts/session.tsx, src/hooks/auth/useAuth.tsx, src/hooks/useGetSessionId.ts, src/hooks/useSession.tsx, src/hooks/useSessionStorage.ts
We want to assign a session id on load of the app which can be persisted through out the whole of the session across browser re-freshes. To acheive this i used session storage which works like local storage but is specific to a browser tab and clears when the tab is closed. 
- Created a hook to use session storage
- Created a hook to get a session id once and store in session stoage
- Update useSession hook to set the session id on the browser 
There is [Demo Here](https://www.loom.com/share/ef656f5a1c9a4fdaa9b5d1b3e8f7021d)
**NOTE: If you have more than one browser tab open each tab will count as a separate session**
**NOTE: Looks like all our cypress tests were not previously running as .only mistakenly committed to the repo.**
=>  CM-807_Keep_session_id_after_refresh

cypress/integration/menubar.spec.ts, src/components/AppBar/MenuDrawer.tsx, src/components/AppBar/MenuPaper.tsx
The menu options for personal values and and retake the quiz should only show when the user has re-taken the quiz. 
It was using session id instead of quiz id - oversight from a previous story. 
Improved cypress tests to check for the correct menu options
=> CM-831 Personal values button only after quiz

src/pages/EmailNewsletterSignUp.tsx, src/pages/Home.tsx
This ticket fixes a couple of minor display issues, merging into Master to release. Will then merge master back into develop
there was an absolute height set on the section which was causing the text to overflow
=> Fix overflowing text on homepage

cypress/integration/personalvalues.spec.ts
Percy snapshot on personal values page is always different due to the animating notification / toast. There are also an number of other animated items on this screen which will make the screen shots always differ. 
I've done a bit of investigation into excluding certain areas of the page from percy, which seems to be possible but wasn't able to get it to work in the time i have.
For just now removing the offending snapshot is the quickest option.
=> Remove_percy_snapshot

src/index.tsx
Hi Danil, 
Just looking a sentry. I have a suggestion on the envirment settings. 
This change should allow us to differentiate between the test, prod, and local envirments. 
What do you think?
=> Update Sentry ENV

src/pages/Login.tsx
There's not yet a ticket for this, just a small issue I noticed after implementing [CM-566: User can reset his forgotten password (Part 1)](https://github.com/ClimateMind/climatemind-frontend/pull/319).
The video below is pretty short, but I just pressed enter while in the text field to enter my email / password. This opened the form to request a reset password link, which shouldn't happen.
https://user-images.githubusercontent.com/78958483/185806697-34d5ed8a-d908-40bb-b146-910adac27e4c.mp4
=> Pressing enter shouldn't open the reset password form

src/pages/userB/HowCMWorks.tsx, src/pages/userB/ShareSummary/ShareSummary.tsx, src/pages/userB/UserBNoConsent/NoConsent.test.tsx, src/pages/userB/UserBNoConsent/UserBNoConsent.tsx
While the route for the 'Not now' button later on in the userB story lead back to the '/shared-impacts' page, the first 'No thanks' did as well, although it should lead back to '/how-cm-works'. This is now fixed.
=> Fix 'No thanks' buttons route

src/pages/userB/ShareSummary/ShareSummary.tsx
Added the 'MORE' button to show the description.
When opened:
=> Add description for top shared value on share summary page

cypress/integration/userBOnboarding/consent.spec.ts, src/pages/userB/ShareSummary/ShareSummary.tsx
First time visiting the summary page:
When pressing the button 'Shared Topics' on the /shared page, it leads back to the summary page but now it only has the 'Create Account' button.
=> Fix routing for the 'Shared Topics' button on the '/shared' page

cypress/integration/accountMenu.ts, src/pages/ClimateFeed.tsx
When refreshing the page, the api call was failing due to a missing sessionId, so now we wait until the sessionId exists.
=> Fix climate feed bug

src/components/PageContentFlex.tsx, src/pages/SubmitSetTwo.tsx
Kameron noticed, that for the two pages /submit and /submit-set-two, a user wasn't able to scoll the page and therefore couldn't continue beacause the button was out of view.
=> Fix page scrolling bugs

.github/dependabot.yml, src/hooks/useCopyLink.ts
Change toast message from 'Link added' to 'Link copied'
=> [Closes #391] Rename toast message for copying link

src/pages/SharedPages/RootPage.tsx, src/pages/UserAUnauthorizedPages/HideAppBarPage.tsx, src/router/Router.tsx
[#563] remove the app bar when doing the conversation and logged in
Explain the **details** of making this change. 
Please provide enough information so that others can review your pull request
Created logic in the router.ts file that allows us to hide the CmAppBar for User B's conversation journey only.  Used location.pathname to get the path of the routes that are applicable. 
Used this to link to a prop in the RoutePage which allows us to pass a boolean to show the CmAppBar
[#562](https://github.com/ClimateMind/climatemind-frontend/issues/562)
closes #562 
- *Part 1*
- *Part 2*
=> [#563 ] - Hide the CmAppBar when doing the User B conversation and logged in or logged out

src/features/auth/components/SignUpForm.tsx
Added and tested Google OAuth logic to Sign up Form.
[#612] - Add Google sign-in feature
closes #612
- *Part 1*
- *Part 2*
=> [#612] - Add Google sign-in feature

nginx.config
adding in line  add_header Content-Security-Policy "script-src 'self' https://www.googletagmanager.com/ https://*.google-analytics.com https://*.analytics.google.com https://www.google.com/ https://www.gstatic.com/ https://accounts.google.com 'unsafe-inline' 'unsafe-eval'";
=> chore: Add Content-Security-Policy header to nginx.config

src/App.tsx, src/features/auth/components/GoogleLogin.tsx, src/features/auth/components/LoginForm.tsx, src/features/auth/components/SignUpForm.tsx, src/features/auth/hooks/useLogin.tsx, src/pages/UserAUnauthorizedPages/LoginPage.tsx, src/pages/UserAUnauthorizedPages/SignUpPage.tsx
Created a custom component called GoogleLogin which uses the google api and CmButton2 for customized google button. 
Have applied the component to the LoginPage and SignUpPage components. I have also added a google provided to the App.tsx file.
Closes [#661]
=> Closes [661] - Customize the google login button
